Table Workspaces {
  id int [pk, increment]
  uuid varchar
  name varchar
}

Table Teams {
  id int [pk, increment]
  workspaceId int [ref: > Workspaces.id]
  uuid varchar
  name varchar
}

Table Projects {
  id int [pk, increment]
  teamId int [ref: > Teams.id]
  uuid varchar
  name varchar
}

Table Tasks {
  id int [pk, increment]
  projectId int [ref: > Projects.id]
  parentTaskId int [ref: > Tasks.id]
  creator_id int [ref: > Users.id]
  assignee_id int [ref: > Users.id]
  uuid varchar
  name varchar
  description text
  due_date datetime
  completed bool
  completed_date datetime
  last_modified datetime
  priority string
}

Table ProjectTasks {
  id int [pk, increment]
  projectId int [ref: > Projects.id]
  taskId int [ref: > Tasks.id]
  uuid varchar
}

Table UserWorkspaces {
  id int [pk, increment]
  workspaceId int [ref: > Workspaces.id]
  userId int [ref: > Users.id]
  uuid varchar
  name varchar
}

Table UserTeams {
  id int [pk, increment]
  teamId int [ref: > Teams.id]
  userId int [ref: > Users.id]
  uuid varchar
  name varchar
}

Table UserProjects {
  id int [pk, increment]
  projectId int [ref: > Projects.id]
  userId int [ref: > Users.id]
  uuid varchar
  name varchar
}

Table Users {
  id int [pk, increment]
  uuid varchar
  name varchar
  email varchar
  passwordHash varchar
  about varchar
}
